[build]
src = "server"
command = "npm start"
language = "nodejs"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd client",
  "rm -f package-lock.json",
  "npm install --no-package-lock --legacy-peer-deps",
  "cd ../server",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd client",
  "npm run build"
]

[start]
cmd = "cd server && npm start"