[build]
builder = "nixpacks"
buildCommand = "cd client && rm -f package-lock.json && npm install --no-package-lock --legacy-peer-deps && NODE_ENV=production REACT_APP_ENV=production GENERATE_SOURCEMAP=false npm run build"

[deploy]
startCommand = "cd server && npm install --legacy-peer-deps && npm start"
restartPolicyType = "on_failure"